<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2014/03/18 18:55:43
return array(

  // sfPropelPlugin_module_libs

  // sfPropelPlugin_lib
  'sfpropelroutecollection' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRouteCollection.class.php',
  'sfpropelroute' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRoute.class.php',
  'sfvalidatorpropelchoice' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoice.class.php',
  'sfvalidatorpropelunique' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelUnique.class.php',
  'sfformfilterpropel' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormFilterPropel.class.php',
  'sfformpropel' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormPropel.class.php',
  'sfpropelbehaviorsymfonybehaviors' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfonyBehaviors.php',
  'sfpropelbehaviorbase' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorBase.php',
  'sfpropelbehaviortimestampable' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorTimestampable.php',
  'sfpropelbehaviori18n' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18n.php',
  'sfpropelbehaviori18ntranslation' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18nTranslation.php',
  'sfpropelbehaviorsymfony' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfony.php',
  'sfwidgetformpropelchoice' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoice.class.php',
  'sfpropelformgenerator' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormGenerator.class.php',
  'sfpropelformfiltergenerator' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormFilterGenerator.class.php',
  'sfpropelgenerator' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php',
  'sfwebdebugpanelpropel' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/debug/sfWebDebugPanelPropel.class.php',
  'sftesterpropel' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/test/sfTesterPropel.class.php',
  'swift_propelspool' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/mailer/Swift_PropelSpool.class.php',
  'sfpropeldata' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelData.class.php',
  'sfpropel' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropel.class.php',
  'sfpropelmanytomany' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelManyToMany.class.php',
  'sfpropelbehavior' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelBehavior.class.php',
  'sfpropeldatabaseschema' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelDatabaseSchema.class.php',
  'sfpropelpager' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelPager.class.php',
  'sfmixer' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfMixer.class.php',
  'sfpropelinsertsqltask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelInsertSqlTask.class.php',
  'sfpropelbuildschematask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSchemaTask.class.php',
  'sfpropelschematoxmltask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToXmlTask.class.php',
  'sfpropelbasetask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBaseTask.class.php',
  'sfpropelgeneratemoduletask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleTask.class.php',
  'sfpropelbuildformstask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFormsTask.class.php',
  'sfpropelbuildmodeltask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildModelTask.class.php',
  'sfphing' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhing.class.php',
  'sfpropelbuildsqltask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSqlTask.class.php',
  'sfpropelbuildalltask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllTask.class.php',
  'sfpropelconfiguredatabasetask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelConfigureDatabaseTask.class.php',
  'sfpropelbuildallloadtask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllLoadTask.class.php',
  'sfpropeldatadumptask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataDumpTask.class.php',
  'sfphinglistener' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhingListener.php',
  'sfpropelschematoymltask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToYmlTask.class.php',
  'sfpropeldataloadtask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataLoadTask.class.php',
  'sfpropelgraphviztask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGraphvizTask.class.php',
  'sfpropelgenerateadmintask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateAdminTask.class.php',
  'sfpropelgeneratemoduleforroutetask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleForRouteTask.class.php',
  'sfpropelbuildfilterstask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFiltersTask.class.php',
  'sfpropelbuildtask' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildTask.class.php',
  'sfpropeldatabase' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/database/sfPropelDatabase.class.php',
  'sfpropellogger' => '/var/www/jobeet/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/log/sfPropelLogger.class.php',

  // project
  'baseform' => '/var/www/jobeet/lib/form/BaseForm.class.php',

  // project_model
  'jobeetcategory' => '/var/www/jobeet/lib/model/JobeetCategory.php',
  'jobeetjob' => '/var/www/jobeet/lib/model/JobeetJob.php',
  'jobeetcategoryaffiliate' => '/var/www/jobeet/lib/model/JobeetCategoryAffiliate.php',
  'jobeetcategorypeer' => '/var/www/jobeet/lib/model/JobeetCategoryPeer.php',
  'jobeetaffiliatepeer' => '/var/www/jobeet/lib/model/JobeetAffiliatePeer.php',
  'jobeetjobtablemap' => '/var/www/jobeet/lib/model/map/JobeetJobTableMap.php',
  'jobeetcategoryaffiliatetablemap' => '/var/www/jobeet/lib/model/map/JobeetCategoryAffiliateTableMap.php',
  'jobeetaffiliatetablemap' => '/var/www/jobeet/lib/model/map/JobeetAffiliateTableMap.php',
  'jobeetcategorytablemap' => '/var/www/jobeet/lib/model/map/JobeetCategoryTableMap.php',
  'jobeetjobpeer' => '/var/www/jobeet/lib/model/JobeetJobPeer.php',
  'basejobeetjob' => '/var/www/jobeet/lib/model/om/BaseJobeetJob.php',
  'basejobeetcategoryaffiliatepeer' => '/var/www/jobeet/lib/model/om/BaseJobeetCategoryAffiliatePeer.php',
  'basejobeetcategoryaffiliate' => '/var/www/jobeet/lib/model/om/BaseJobeetCategoryAffiliate.php',
  'basejobeetjobpeer' => '/var/www/jobeet/lib/model/om/BaseJobeetJobPeer.php',
  'basejobeetcategory' => '/var/www/jobeet/lib/model/om/BaseJobeetCategory.php',
  'basejobeetaffiliate' => '/var/www/jobeet/lib/model/om/BaseJobeetAffiliate.php',
  'basejobeetcategorypeer' => '/var/www/jobeet/lib/model/om/BaseJobeetCategoryPeer.php',
  'basejobeetaffiliatepeer' => '/var/www/jobeet/lib/model/om/BaseJobeetAffiliatePeer.php',
  'jobeetcategoryaffiliatepeer' => '/var/www/jobeet/lib/model/JobeetCategoryAffiliatePeer.php',
  'jobeetaffiliate' => '/var/www/jobeet/lib/model/JobeetAffiliate.php',

  // application
  'myuser' => '/var/www/jobeet/apps/frontend/lib/myUser.class.php',

  // modules
);
